fix: check branch name

diff --git a/.github/workflows/fail.yml b/.github/workflows/fail.yml
--- a/.github/workflows/fail.yml
+++ b/.github/workflows/fail.yml
@@ -34,28 +34,29 @@ jobs:
         run: |
           echo ${{ steps.comment-branch.outputs.head_ref }}
           echo ${{ github.head_ref }}
-          echo ${{ steps.comment-branch.outputs.head_ref || github.head_ref }}
+          echo ${{ github.ref_name }}
+          echo ${{ steps.comment-branch.outputs.head_ref || github.head_ref || github.ref_name }}
 
-      - name: Get tag
-        id: get_tag
-        uses: oprypin/find-latest-tag@v1
-        continue-on-error: true
-        with:
-          repository: ${{ github.repository }}
-          regex: '(.*)${{ steps.comment-branch.outputs.head_ref || github.head_ref }}(.*)'
+      # - name: Get tag
+      #   id: get_tag
+      #   uses: oprypin/find-latest-tag@v1
+      #   continue-on-error: true
+      #   with:
+      #     repository: ${{ github.repository }}
+      #     regex: '(.*)${{ steps.comment-branch.outputs.head_ref || github.head_ref }}(.*)'
  
-      - name: Check prerelease cleanup
-        if: ${{ steps.get_tag.outputs.tag }}
-        run: |
-          echo "ERROR: Run full cleanup to merge"
-          echo "Found tag ${{ steps.get_tag.outputs.tag }}"
-          echo "To run full cleanup, comment /cleanup on your PR"
-          exit 1
+      # - name: Check prerelease cleanup
+      #   if: ${{ steps.get_tag.outputs.tag }}
+      #   run: |
+      #     echo "ERROR: Run full cleanup to merge"
+      #     echo "Found tag ${{ steps.get_tag.outputs.tag }}"
+      #     echo "To run full cleanup, comment /cleanup on your PR"
+      #     exit 1
 
-      - name: Set latest commit status as ${{ job.status }}
-        uses: myrotvorets/set-commit-status-action@master
-        if: steps.comment-branch.outputs.head_ref
-        with:
-          sha: ${{ steps.comment-branch.outputs.head_sha }}
-          token: ${{ secrets.GITHUB_TOKEN }}
-          status: ${{ job.status }}
+      # - name: Set latest commit status as ${{ job.status }}
+      #   uses: myrotvorets/set-commit-status-action@master
+      #   if: steps.comment-branch.outputs.head_ref
+      #   with:
+      #     sha: ${{ steps.comment-branch.outputs.head_sha }}
+      #     token: ${{ secrets.GITHUB_TOKEN }}
+      #     status: ${{ job.status }}
